# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Configure GitHub Token
        env:
          GOPRIVATE: github.com/BeloTechnologies/*
          GONOSUMDB: github.com/BeloTechnologies/*
          GITHUB_TOKEN: ${{ secrets.BELO_CI }}
        run: |
          echo "machine github.com login ${GITHUB_ACTOR} password ${GITHUB_TOKEN}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
